version: '2.3'
services:
    daemon:
      ##
      # --Pterodactyl Daemon--
      # This service provides the wings runtime.
      ##
      environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
      image: docker.io/ccarney16/pterodactyl-daemon:latest
      ports:
      - 2022:2022
      - 8080:8080
      privileged: true
      restart: always
      volumes:
      - ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}:${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}

      - /tmp/pterodactyl/:/tmp/pterodactyl/
    
      # Enable Let's Encrypt Support
      - ./conf.d/daemon:/etc/pterodactyl
      - ./conf.d/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d/certs:/etc/certs:ro
      working_dir: ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
