###
# Optional Project Dependencies for Pterodactyl
#
# This compose file provides the required dependencies for 
# Pterodactyl, such as MariaDB and Redis.
##
version: '2.3'
services:
    ##
    # --MariaDB--
    # Required for the control panel to work.
    # Stores Server/User information
    ##
    mysql:
      image: docker.io/library/mariadb:10.5
      env_file: ./conf.d/mariadb.env
      ports:
      - ${MYSQL_ADDRESS:-3306}
      restart: always
      volumes:
      - ./data/db:/var/lib/mysql
